### PR TITLE
PR use directory package.json

### PR DESCRIPTION
**Pull request by mikeerickson**
- [x] Add support for getting version of current directory (using period as patter)
- [x] Updated Inline Description
- [x] Updated readme.md

   ```
   $ latest-version .
   1.1.1 <-- returns current directory package.json version
   ```

### CODE REVIEW

**Comment by sindresorhus** [comment]
Why?

**Comment by mikeerickson** [comment]
Often when working on my various modules, I often check version.  Makes it easier than having to open the package.json to review version property.

**Comment by mikeerickson** [comment]
@sindresorhus OK, I have re-read what this project does and I can now see that this PR doesn't make sense after all.  I will craft a simple CLI to do what I actually need.

**Comment by sindresorhus** [comment]
Yeah. I usually just do `cat package.json`. I would call it `pkg-version`.

**Comment by mikeerickson** [comment]
Works for me, sorry for the noise.

**Pull request closed without merging**
